[Position]
x = "float"
y = "float"
z = "float"

[Rotation]
x = "float"
y = "float"
z = "float"
w = "float"

[Color]
x = "float"
y = "float"
z = "float"

[Camera]
fov = "float"
near = "float"
far = "float"

[Model]
shader = "path"
submeshes = "SubMesh*"
submesh_count = "size_t"
drawsBuffer = "GLuint"


[Material]
shader_id = "GLuint"

[Input]
x = "float"
y = "float"
z = "float"

[Velocity]
linear = "glm::vec3"
angular = "glm::vec3"

[ForceAccumulator]
force = "glm::vec3"
torque = "glm::vec3"

[RigidBody]
linearDamping = "float"
angularDamping = "float"

[Collider]
x = "float"
y = "float"
z = "float"

[Texture]
x = "float"
y = "float"
z = "float"

[Mass]
inv = "float"

[Gravity]
value = "float"