[camera]
camera = { fov = 70, near = 0.1, far = 1000 }
position = { x = 0, y = 0, z = 1 }
rotation = { pitch = 0.00, yaw = 60, roll = 90 }

[floor1]
model    = "assets/models/wall.gltf"
material = "skinned"
texture  = "dungeon_texture.png"
position = { x = 0.00, y = 0.00, z = 0.00 }
rotation = { pitch = 0.00, yaw = 0.00, roll = 0.00 }
