[camera]
camera = { fov = 70, near = 0.1, far = 1000 }
position = { x = -1, y = 1, z = 2 }
rotation = { pitch = 30, yaw = 0, roll = 0 }

[wall]
model    = {model = "assets/models/static/wall.glb"}
material = {shader ="unlit"}
texture  = {image ="dungeon_texture.png"}
position = { x = 1, y = 0, z = 0 }
rbody = { invMass = 1.0 }
rotation = { pitch = 0.00, yaw = 0.00, roll = 0.00 }

[player]
model    = { model = "assets/models/static/player.glb"}
material = "unlit"
texture  = "dungeon_texture.png"
position = { x = 1, y = 0, z = 4 }
rotation = { pitch = 0.00, yaw = 0.00, roll = 0.00 }
rbody = { invMass = 1.0}
input = "keyboard"

[floor]
model    = "assets/models/static/wall.glb"
material = "unlit"
texture  = "dungeon_texture.png"
position = { x = 6, y = 0, z = 0 }
rotation = { pitch = 0.00, yaw = 0.00, roll = 0.00 }
rbody = { invMass = 0.0}
collider = {shape = "box", x = 0, y=0, z=0, w=10, h=5, d=3 }