[camera]
camera = { fov = 90, near = 0.1, far = 1000 }
position = { x = -1, y = 0, z = 0 }
rotation = { pitch = 0.00, yaw = 60, roll = 90 }

[floor1]
model    = "assets\\models\\static\\wall.glb"
material = "phong"
texture  = "dungeon_texture.png"
position = { x = 5, y = 1, z = 1 }
rotation = { pitch = 0.00, yaw = 0.00, roll = 0.00 }
